/**
 * Regenerates testdata/crypto-vectors.json, the file that keeps internal/envelope honest.
 *
 * The browser is the reference implementation: every ciphertext already written was
 * produced by it, so the Go side has to match these bytes rather than the other way round.
 * Run it the way swagger is regenerated — deliberately, and commit the result:
 *
 *     cd web && npx vite-node scripts/gen-vectors.ts
 *
 * A diff in the output means a frozen format moved. That is either a mistake, or a change
 * that has to be paired with a migration of everything already sealed.
 */
import { writeFileSync } from 'node:fs';
import { fileURLToPath, URL } from 'node:url';

import { encrypt, importKey, type Sealed } from '@/crypto/aead';
import { bytesToB64, pad, PAD_BLOCK, utf8 } from '@/crypto/bytes';
import {
  aad,
  type EntityRef,
  encryptContent,
  encryptMeta,
  type EntityMeta,
  sealInfo,
} from '@/crypto/envelope';
import { fingerprint, generateIdentity, splitPublicBlob } from '@/crypto/identity';
import { generateKey as generateMasterKey } from '@/crypto/aead';
import { seal } from '@/crypto/sealedbox';
import { revisionPayload, signRevision } from '@/crypto/signature';

const OUT = fileURLToPath(new URL('../../testdata/crypto-vectors.json', import.meta.url));

// Fixed so the file is stable between runs: a vector that changes every time proves nothing
// and turns every regeneration into an unreviewable diff.
const VAULT_ID = 7;
const NOTE_UID = '3f2b8c14-9d5e-4a71-8b0c-6e2d5a19f4c3';
const SCOPE_UID = 'c81f0a67-2b34-4e59-9d7a-1f6b3c8e50d2';
const KEY = new Uint8Array(32).map((_, i) => (i * 7 + 13) & 0xff);

const b64 = bytesToB64;
const sealedOf = (s: Sealed) => ({ ciphertext_b64: b64(s.ciphertext), nonce_b64: b64(s.nonce) });
const refOf = (r: EntityRef) => ({
  vault_id: r.vaultId,
  entity: r.entity,
  entity_id: r.entityId,
  scope_client_id: r.scopeClientId,
  key_version: r.keyVersion,
});

const noteRef: EntityRef = {
  vaultId: VAULT_ID,
  entity: 'file',
  entityId: NOTE_UID,
  scopeClientId: SCOPE_UID,
  keyVersion: 2,
};

// The vault's own name is sealed before a serial id exists, so it is bound to vaultId 0 —
// here as at creation. Getting this wrong on the Go side means every vault name is locked.
const vaultRef: EntityRef = {
  vaultId: 0,
  entity: 'vault',
  entityId: SCOPE_UID,
  scopeClientId: SCOPE_UID,
  keyVersion: 1,
};

const metas: EntityMeta[] = [
  { name: 'Decisions' },
  { name: 'Notes', icon: 'book' },
  { name: 'Проект «Альфа» — 日本語', icon: 'target', tags: ['alpha', 'wip'] },
  // Go escapes <, > and & in JSON by default and the browser does not. A note called
  // "R&D <draft>" is the cheapest way to keep that difference from going unnoticed.
  { name: 'R&D <draft>', tags: ['a&b'] },
];

async function main(): Promise<void> {
  const key = await importKey(KEY);

  const body = '# Heading\n\nA body with a [[wikilink]] and some UTF-8: ёжик, 日本語.\n';

  const aeadPlain = utf8('the quick brown fox');
  const aeadAad = aad(noteRef);
  const aeadSealed = await encrypt(key, aeadPlain, aeadAad);

  const identity = (await generateIdentity(await generateMasterKey())).identity;
  const sealPublic = splitPublicBlob(identity.publicBlob).seal;

  const scopeKey = new Uint8Array(32).map((_, i) => (i * 31 + 5) & 0xff);
  const info = sealInfo(SCOPE_UID, 2);
  const box = await seal(sealPublic, scopeKey, info);

  const contentSeq = 42;
  const contentSealed = await encryptContent(key, body, noteRef);
  const signature = await signRevision(identity, noteRef, contentSeq, contentSealed);

  const vectors = {
    version: 1,
    note: 'Generated by web/scripts/gen-vectors.ts. The browser is the reference; Go matches it.',

    key_b64: b64(KEY),

    aad: [noteRef, vaultRef].map((ref) => ({ ref: refOf(ref), expected_b64: b64(aad(ref)) })),

    seal_info: [
      { scope_client_id: SCOPE_UID, key_version: 2, expected: sealInfo(SCOPE_UID, 2) },
      { scope_client_id: SCOPE_UID, key_version: 1, expected: sealInfo(SCOPE_UID, 1) },
    ],

    // An empty body still costs a whole block: the framing is what hides the length.
    pad: ['', 'x', body, 'y'.repeat(PAD_BLOCK)].map((value) => ({
      input_b64: b64(utf8(value)),
      block: PAD_BLOCK,
      expected_b64: b64(pad(utf8(value))),
    })),

    // icon and tags are left out rather than written empty, so a note that never had tags
    // seals to the bytes it always did.
    meta_json: metas.map((meta) => ({ meta, expected: JSON.stringify(meta) })),

    aead: [
      {
        key_b64: b64(KEY),
        aad_b64: b64(aeadAad),
        plaintext_b64: b64(aeadPlain),
        ...sealedOf(aeadSealed),
      },
    ],

    envelope_meta: await Promise.all(
      metas.map(async (meta) => ({
        ref: refOf(noteRef),
        meta,
        ...sealedOf(await encryptMeta(key, meta, noteRef)),
      })),
    ),

    envelope_content: [
      { ref: refOf(noteRef), body, ...sealedOf(contentSealed) },
      { ref: refOf(vaultRef), body: '', ...sealedOf(await encryptContent(key, '', vaultRef)) },
    ],

    sealed_box: [
      {
        info,
        recipient_public_blob_b64: b64(identity.publicBlob),
        recipient_bundle_b64: b64(await bundleOf(identity)),
        payload_b64: b64(scopeKey),
        blob_b64: b64(box.blob),
        nonce_b64: b64(box.nonce),
      },
    ],

    fingerprint: [
      {
        public_blob_b64: b64(identity.publicBlob),
        expected: await fingerprint(identity.publicBlob),
      },
    ],

    revision_signature: [
      {
        public_blob_b64: b64(identity.publicBlob),
        ref: refOf(noteRef),
        content_seq: contentSeq,
        ...sealedOf(contentSealed),
        payload_b64: b64(revisionPayload(noteRef, contentSeq, contentSealed)),
        signature_b64: b64(signature),
      },
    ],
  };

  writeFileSync(OUT, `${JSON.stringify(vectors, null, 2)}\n`);
  process.stdout.write(`wrote ${OUT}\n`);
}

/** The private half in the shape unwrapIdentity reads: format byte, then two PKCS#8 keys. */
async function bundleOf(identity: {
  sealPrivate: CryptoKey;
  signPrivate: CryptoKey;
}): Promise<Uint8Array> {
  const parts = await Promise.all(
    [identity.sealPrivate, identity.signPrivate].map(async (key) => {
      const pkcs8 = new Uint8Array(await crypto.subtle.exportKey('pkcs8', key));
      const header = new Uint8Array(2);
      new DataView(header.buffer).setUint16(0, pkcs8.length, false);

      return [header, pkcs8];
    }),
  );

  const flat = [Uint8Array.of(0x01), ...parts.flat()];
  const out = new Uint8Array(flat.reduce((sum, part) => sum + part.length, 0));

  let offset = 0;
  for (const part of flat) {
    out.set(part, offset);
    offset += part.length;
  }

  return out;
}

await main();
