// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Shelf Backend",
            "email": "dmitr.murygin@gmail.com"
        },
        "license": {
            "name": "Proprietary"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/auth/keys": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns the wrapped keys: the client needs them after a restart while the access token is still alive.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Cryptographic material of the user",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/auth.KeysResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/auth/login": {
            "post": {
                "description": "Verifies auth_hash and returns the wrapped keys together with a token pair.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Login",
                "parameters": [
                    {
                        "description": "Login and auth_hash",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.loginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/auth.SessionResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/auth/logout": {
            "post": {
                "description": "Revokes the session the refresh token belongs to.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Logout",
                "parameters": [
                    {
                        "description": "Refresh token",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.refreshRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/auth/logout-all": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Logout on every device",
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/auth/me": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Current user",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/auth.UserResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/auth/password": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Accepts the master key re-encrypted with the new wrapping key. All sessions are revoked and the response carries a new token pair.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Password change",
                "parameters": [
                    {
                        "description": "New authentication data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.changePasswordRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/auth.TokensResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/auth/prelogin": {
            "post": {
                "description": "Returns the salt and the KDF parameters the client needs to compute auth_hash.\nFor an unknown login it returns plausible values so the endpoint does not reveal whether the account exists.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Key derivation parameters",
                "parameters": [
                    {
                        "description": "Login",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.preloginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/auth.PreloginResponse"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/auth/recovery/complete": {
            "post": {
                "description": "Sets the new authentication data using the token issued by recovery/start.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Access recovery completion",
                "parameters": [
                    {
                        "description": "New authentication data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.recoveryCompleteRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/auth.TokensResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/auth/recovery/start": {
            "post": {
                "description": "Verifies ownership of the recovery code and returns the master key wrapped with it\ntogether with a short-lived token for completing the recovery.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Access recovery start",
                "parameters": [
                    {
                        "description": "Login and recovery code verifier",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.recoveryStartRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/auth.RecoveryChallengeResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/auth/refresh": {
            "post": {
                "description": "Exchanges a refresh token for a new pair. The token is single-use: presenting it again revokes all sessions.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Token pair refresh",
                "parameters": [
                    {
                        "description": "Refresh token",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.refreshRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/auth.TokensResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/auth/register": {
            "post": {
                "description": "Creates an account from the cryptographic material prepared by the client and opens a session.\nThe server never sees the password: the client derives the master key wrapping key and auth_hash from it.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Registration",
                "parameters": [
                    {
                        "description": "Registration data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.registerRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/auth.SessionResponse"
                        }
                    },
                    "409": {
                        "description": "Login is already taken",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/auth/sessions": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Active sessions",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/auth.DevicesResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/auth/sessions/{id}": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Session revocation",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Session identifier",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/files/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "files"
                ],
                "summary": "Read a note",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "file id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/vault.FileResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "files"
                ],
                "summary": "Trash a note",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "file id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "files"
                ],
                "summary": "Update note metadata",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "file id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "encrypted note metadata",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/vault.updateMetaRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/vault.FileResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/files/{id}/content": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "files"
                ],
                "summary": "Write a note body",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "file id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "content sequence the client last saw",
                        "name": "If-Match",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "encrypted body",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/vault.updateContentRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/vault.ContentResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "428": {
                        "description": "Precondition Required",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/files/{id}/move": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "files"
                ],
                "summary": "Move a note",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "file id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "destination folder",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/vault.moveRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/vault.FileResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/files/{id}/purge": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "files"
                ],
                "summary": "Purge a note",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "file id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/files/{id}/restore": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "files"
                ],
                "summary": "Restore a note",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "file id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    }
                }
            }
        },
        "/api/v1/folders/{id}": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "folders"
                ],
                "summary": "Trash a folder",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "folder id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "folders"
                ],
                "summary": "Update folder metadata",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "folder id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "encrypted folder metadata",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/vault.updateMetaRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/vault.FolderResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/folders/{id}/move": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "folders"
                ],
                "summary": "Move a folder",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "folder id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "destination",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/vault.moveRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/vault.FolderResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/folders/{id}/purge": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "folders"
                ],
                "summary": "Purge a folder",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "folder id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/folders/{id}/restore": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "folders"
                ],
                "summary": "Restore a folder",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "folder id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    }
                }
            }
        },
        "/api/v1/vaults": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "vaults"
                ],
                "summary": "List vaults",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/vault.VaultsResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "vaults"
                ],
                "summary": "Create a vault",
                "parameters": [
                    {
                        "description": "vault metadata and the content key sealed to the creator",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/vault.createVaultRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/vault.VaultResponse"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/vaults/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "vaults"
                ],
                "summary": "Read a vault",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "vault id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/vault.VaultResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "vaults"
                ],
                "summary": "Delete a vault",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "vault id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "vaults"
                ],
                "summary": "Update vault metadata",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "vault id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "encrypted metadata",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/vault.updateMetaRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/vaults/{id}/files": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "files"
                ],
                "summary": "Create a note",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "vault id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "encrypted note",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/vault.createFileRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/vault.FileResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/vaults/{id}/files/bulk": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "files"
                ],
                "summary": "Read notes in bulk",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "vault id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "note ids, at most 200",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/vault.bulkFilesRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/vault.FilesResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/vaults/{id}/folders": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "folders"
                ],
                "summary": "Create a folder",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "vault id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "encrypted folder metadata",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/vault.createFolderRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/vault.FolderResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/vaults/{id}/keys": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "vaults"
                ],
                "summary": "List the caller's key grants",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "vault id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/vault.KeyGrantsResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/vaults/{id}/scopes": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "vaults"
                ],
                "summary": "List key scopes",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "vault id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/vault.ScopesResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/vaults/{id}/trash": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "vaults"
                ],
                "summary": "Read the trash",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "vault id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/vault.TreeResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/vaults/{id}/tree": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "vaults"
                ],
                "summary": "Read the vault tree",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "vault id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/vault.TreeResponse"
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "Returns 200 while the process is alive. Does not check external dependencies.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "system"
                ],
                "summary": "Liveness probe",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.HealthResponse"
                        }
                    }
                }
            }
        },
        "/ready": {
            "get": {
                "description": "Checks that PostgreSQL is reachable. Returns 503 if the database is unavailable.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "system"
                ],
                "summary": "Readiness probe",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.HealthResponse"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "api.HealthResponse": {
            "type": "object",
            "properties": {
                "service": {
                    "type": "string",
                    "example": "shelf-backend"
                },
                "status": {
                    "type": "string",
                    "example": "ok"
                }
            }
        },
        "auth.DeviceResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "current": {
                    "type": "boolean",
                    "example": true
                },
                "expires_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer",
                    "example": 12
                },
                "ip": {
                    "type": "string",
                    "example": "203.0.113.7"
                },
                "last_used_at": {
                    "type": "string"
                },
                "user_agent": {
                    "type": "string"
                }
            }
        },
        "auth.DevicesResponse": {
            "type": "object",
            "properties": {
                "sessions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/auth.DeviceResponse"
                    }
                }
            }
        },
        "auth.KDFParams": {
            "type": "object",
            "properties": {
                "algorithm": {
                    "type": "string"
                },
                "iterations": {
                    "type": "integer"
                },
                "memory": {
                    "type": "integer"
                },
                "parallelism": {
                    "type": "integer"
                }
            }
        },
        "auth.KeysResponse": {
            "type": "object",
            "properties": {
                "kdf_params": {
                    "$ref": "#/definitions/auth.KDFParams"
                },
                "kdf_salt": {
                    "type": "array",
                    "items": {
                        "type": "integer",
                        "format": "byte"
                    }
                },
                "master_key_nonce": {
                    "type": "array",
                    "items": {
                        "type": "integer",
                        "format": "byte"
                    }
                },
                "private_key_nonce": {
                    "type": "array",
                    "items": {
                        "type": "integer",
                        "format": "byte"
                    }
                },
                "public_key": {
                    "type": "array",
                    "items": {
                        "type": "integer",
                        "format": "byte"
                    }
                },
                "wrapped_master_key": {
                    "type": "array",
                    "items": {
                        "type": "integer",
                        "format": "byte"
                    }
                },
                "wrapped_private_key": {
                    "type": "array",
                    "items": {
                        "type": "integer",
                        "format": "byte"
                    }
                }
            }
        },
        "auth.PreloginResponse": {
            "type": "object",
            "properties": {
                "kdf_params": {
                    "$ref": "#/definitions/auth.KDFParams"
                },
                "kdf_salt": {
                    "type": "array",
                    "items": {
                        "type": "integer",
                        "format": "byte"
                    }
                }
            }
        },
        "auth.RecoveryChallengeResponse": {
            "type": "object",
            "properties": {
                "expires_at": {
                    "type": "string"
                },
                "nonce": {
                    "type": "array",
                    "items": {
                        "type": "integer",
                        "format": "byte"
                    }
                },
                "recovery_token": {
                    "type": "string"
                },
                "wrapped_master_key": {
                    "type": "array",
                    "items": {
                        "type": "integer",
                        "format": "byte"
                    }
                }
            }
        },
        "auth.SessionResponse": {
            "type": "object",
            "properties": {
                "keys": {
                    "$ref": "#/definitions/auth.KeysResponse"
                },
                "tokens": {
                    "$ref": "#/definitions/auth.TokensResponse"
                },
                "user": {
                    "$ref": "#/definitions/auth.UserResponse"
                }
            }
        },
        "auth.TokensResponse": {
            "type": "object",
            "properties": {
                "access_expires_at": {
                    "type": "string"
                },
                "access_token": {
                    "type": "string"
                },
                "refresh_expires_at": {
                    "type": "string"
                },
                "refresh_token": {
                    "type": "string"
                },
                "token_type": {
                    "type": "string",
                    "example": "Bearer"
                }
            }
        },
        "auth.UserResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "display_name": {
                    "type": "string",
                    "example": "Dmitry Murygin"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "login": {
                    "type": "string",
                    "example": "dmitry"
                }
            }
        },
        "auth.changePasswordRequest": {
            "type": "object",
            "required": [
                "auth_hash",
                "current_auth_hash",
                "kdf_params",
                "kdf_salt",
                "master_key_nonce",
                "wrapped_master_key"
            ],
            "properties": {
                "auth_hash": {
                    "type": "array",
                    "maxItems": 128,
                    "minItems": 16,
                    "items": {
                        "type": "integer",
                        "format": "byte"
                    }
                },
                "current_auth_hash": {
                    "type": "array",
                    "maxItems": 128,
                    "minItems": 16,
                    "items": {
                        "type": "integer",
                        "format": "byte"
                    }
                },
                "kdf_params": {
                    "$ref": "#/definitions/auth.kdfParams"
                },
                "kdf_salt": {
                    "type": "array",
                    "maxItems": 64,
                    "minItems": 16,
                    "items": {
                        "type": "integer",
                        "format": "byte"
                    }
                },
                "master_key_nonce": {
                    "type": "array",
                    "maxItems": 32,
                    "minItems": 12,
                    "items": {
                        "type": "integer",
                        "format": "byte"
                    }
                },
                "recovery": {
                    "$ref": "#/definitions/auth.recoveryKey"
                },
                "wrapped_master_key": {
                    "type": "array",
                    "maxItems": 1024,
                    "minItems": 32,
                    "items": {
                        "type": "integer",
                        "format": "byte"
                    }
                }
            }
        },
        "auth.kdfParams": {
            "type": "object",
            "required": [
                "algorithm",
                "iterations",
                "memory",
                "parallelism"
            ],
            "properties": {
                "algorithm": {
                    "type": "string",
                    "enum": [
                        "argon2id"
                    ],
                    "example": "argon2id"
                },
                "iterations": {
                    "type": "integer",
                    "maximum": 16,
                    "minimum": 2,
                    "example": 3
                },
                "memory": {
                    "type": "integer",
                    "minimum": 19456,
                    "example": 65536
                },
                "parallelism": {
                    "type": "integer",
                    "maximum": 16,
                    "minimum": 1,
                    "example": 2
                }
            }
        },
        "auth.loginRequest": {
            "type": "object",
            "required": [
                "auth_hash",
                "login"
            ],
            "properties": {
                "auth_hash": {
                    "type": "array",
                    "maxItems": 128,
                    "minItems": 16,
                    "items": {
                        "type": "integer",
                        "format": "byte"
                    }
                },
                "login": {
                    "type": "string",
                    "maxLength": 64,
                    "minLength": 3,
                    "example": "dmitry"
                }
            }
        },
        "auth.preloginRequest": {
            "type": "object",
            "required": [
                "login"
            ],
            "properties": {
                "login": {
                    "type": "string",
                    "maxLength": 64,
                    "minLength": 3,
                    "example": "dmitry"
                }
            }
        },
        "auth.recoveryCompleteRequest": {
            "type": "object",
            "required": [
                "auth_hash",
                "kdf_params",
                "kdf_salt",
                "master_key_nonce",
                "recovery_token",
                "wrapped_master_key"
            ],
            "properties": {
                "auth_hash": {
                    "type": "array",
                    "maxItems": 128,
                    "minItems": 16,
                    "items": {
                        "type": "integer",
                        "format": "byte"
                    }
                },
                "kdf_params": {
                    "$ref": "#/definitions/auth.kdfParams"
                },
                "kdf_salt": {
                    "type": "array",
                    "maxItems": 64,
                    "minItems": 16,
                    "items": {
                        "type": "integer",
                        "format": "byte"
                    }
                },
                "master_key_nonce": {
                    "type": "array",
                    "maxItems": 32,
                    "minItems": 12,
                    "items": {
                        "type": "integer",
                        "format": "byte"
                    }
                },
                "recovery": {
                    "$ref": "#/definitions/auth.recoveryKey"
                },
                "recovery_token": {
                    "type": "string"
                },
                "wrapped_master_key": {
                    "type": "array",
                    "maxItems": 1024,
                    "minItems": 32,
                    "items": {
                        "type": "integer",
                        "format": "byte"
                    }
                }
            }
        },
        "auth.recoveryKey": {
            "type": "object",
            "required": [
                "auth_hash",
                "nonce",
                "wrapped_master_key"
            ],
            "properties": {
                "auth_hash": {
                    "type": "array",
                    "maxItems": 128,
                    "minItems": 16,
                    "items": {
                        "type": "integer",
                        "format": "byte"
                    }
                },
                "nonce": {
                    "type": "array",
                    "maxItems": 32,
                    "minItems": 12,
                    "items": {
                        "type": "integer",
                        "format": "byte"
                    }
                },
                "wrapped_master_key": {
                    "type": "array",
                    "maxItems": 1024,
                    "minItems": 32,
                    "items": {
                        "type": "integer",
                        "format": "byte"
                    }
                }
            }
        },
        "auth.recoveryStartRequest": {
            "type": "object",
            "required": [
                "login",
                "recovery_auth_hash"
            ],
            "properties": {
                "login": {
                    "type": "string",
                    "maxLength": 64,
                    "minLength": 3,
                    "example": "dmitry"
                },
                "recovery_auth_hash": {
                    "description": "AuthHash is derived by the client from the recovery code and serves as the verifier.",
                    "type": "array",
                    "maxItems": 128,
                    "minItems": 16,
                    "items": {
                        "type": "integer",
                        "format": "byte"
                    }
                }
            }
        },
        "auth.refreshRequest": {
            "type": "object",
            "required": [
                "refresh_token"
            ],
            "properties": {
                "refresh_token": {
                    "type": "string",
                    "maxLength": 256,
                    "minLength": 16
                }
            }
        },
        "auth.registerRequest": {
            "type": "object",
            "required": [
                "auth_hash",
                "display_name",
                "kdf_params",
                "kdf_salt",
                "login",
                "master_key_nonce",
                "private_key_nonce",
                "public_key",
                "recovery",
                "wrapped_master_key",
                "wrapped_private_key"
            ],
            "properties": {
                "auth_hash": {
                    "type": "array",
                    "maxItems": 128,
                    "minItems": 16,
                    "items": {
                        "type": "integer",
                        "format": "byte"
                    }
                },
                "display_name": {
                    "type": "string",
                    "maxLength": 128,
                    "minLength": 1,
                    "example": "Dmitry Murygin"
                },
                "kdf_params": {
                    "$ref": "#/definitions/auth.kdfParams"
                },
                "kdf_salt": {
                    "type": "array",
                    "maxItems": 64,
                    "minItems": 16,
                    "items": {
                        "type": "integer",
                        "format": "byte"
                    }
                },
                "login": {
                    "type": "string",
                    "maxLength": 64,
                    "minLength": 3,
                    "example": "dmitry"
                },
                "master_key_nonce": {
                    "type": "array",
                    "maxItems": 32,
                    "minItems": 12,
                    "items": {
                        "type": "integer",
                        "format": "byte"
                    }
                },
                "private_key_nonce": {
                    "type": "array",
                    "maxItems": 32,
                    "minItems": 12,
                    "items": {
                        "type": "integer",
                        "format": "byte"
                    }
                },
                "public_key": {
                    "type": "array",
                    "maxItems": 1024,
                    "minItems": 32,
                    "items": {
                        "type": "integer",
                        "format": "byte"
                    }
                },
                "recovery": {
                    "$ref": "#/definitions/auth.recoveryKey"
                },
                "wrapped_master_key": {
                    "type": "array",
                    "maxItems": 1024,
                    "minItems": 32,
                    "items": {
                        "type": "integer",
                        "format": "byte"
                    }
                },
                "wrapped_private_key": {
                    "type": "array",
                    "maxItems": 1024,
                    "minItems": 32,
                    "items": {
                        "type": "integer",
                        "format": "byte"
                    }
                }
            }
        },
        "response.Error": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string",
                    "example": "not_found"
                },
                "details": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "message": {
                    "type": "string",
                    "example": "resource not found"
                },
                "request_id": {
                    "type": "string",
                    "example": "1f8c1a5e-2b3d-4d6a-9c0e-5f5a5a7d1234"
                }
            }
        },
        "response.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "$ref": "#/definitions/response.Error"
                }
            }
        },
        "vault.ContentResponse": {
            "type": "object",
            "properties": {
                "content_seq": {
                    "type": "integer",
                    "example": 15
                },
                "updated_at": {
                    "type": "string"
                },
                "updated_seq": {
                    "type": "integer",
                    "example": 43
                }
            }
        },
        "vault.FileResponse": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "array",
                    "items": {
                        "type": "integer",
                        "format": "byte"
                    }
                },
                "content_nonce": {
                    "type": "array",
                    "items": {
                        "type": "integer",
                        "format": "byte"
                    }
                },
                "content_seq": {
                    "type": "integer",
                    "example": 14
                },
                "content_size": {
                    "type": "integer",
                    "example": 8192
                },
                "created_at": {
                    "type": "string"
                },
                "deleted_at": {
                    "type": "string"
                },
                "folder_id": {
                    "type": "integer"
                },
                "grant_count": {
                    "type": "integer",
                    "example": 1
                },
                "id": {
                    "type": "integer",
                    "example": 88
                },
                "inherit_access": {
                    "type": "boolean",
                    "example": true
                },
                "key_scope_id": {
                    "type": "integer",
                    "example": 1
                },
                "key_version": {
                    "type": "integer",
                    "example": 1
                },
                "meta": {
                    "type": "array",
                    "items": {
                        "type": "integer",
                        "format": "byte"
                    }
                },
                "meta_nonce": {
                    "type": "array",
                    "items": {
                        "type": "integer",
                        "format": "byte"
                    }
                },
                "own_scope": {
                    "type": "boolean",
                    "example": false
                },
                "permission": {
                    "type": "string",
                    "example": "edit"
                },
                "updated_at": {
                    "type": "string"
                },
                "updated_by": {
                    "type": "integer"
                },
                "updated_seq": {
                    "type": "integer",
                    "example": 42
                },
                "vault_id": {
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "vault.FilesResponse": {
            "type": "object",
            "properties": {
                "files": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/vault.FileResponse"
                    }
                }
            }
        },
        "vault.FolderResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "deleted_at": {
                    "type": "string"
                },
                "depth": {
                    "type": "integer",
                    "example": 0
                },
                "grant_count": {
                    "type": "integer",
                    "example": 1
                },
                "id": {
                    "type": "integer",
                    "example": 12
                },
                "inherit_access": {
                    "type": "boolean",
                    "example": true
                },
                "key_scope_id": {
                    "type": "integer",
                    "example": 1
                },
                "key_version": {
                    "type": "integer",
                    "example": 1
                },
                "meta": {
                    "type": "array",
                    "items": {
                        "type": "integer",
                        "format": "byte"
                    }
                },
                "meta_nonce": {
                    "type": "array",
                    "items": {
                        "type": "integer",
                        "format": "byte"
                    }
                },
                "own_scope": {
                    "type": "boolean",
                    "example": false
                },
                "parent_id": {
                    "type": "integer"
                },
                "permission": {
                    "type": "string",
                    "example": "own"
                },
                "position": {
                    "type": "integer",
                    "example": 0
                },
                "updated_at": {
                    "type": "string"
                },
                "updated_by": {
                    "type": "integer"
                },
                "updated_seq": {
                    "type": "integer",
                    "example": 41
                },
                "vault_id": {
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "vault.KeyGrantResponse": {
            "type": "object",
            "properties": {
                "key_version": {
                    "type": "integer",
                    "example": 1
                },
                "nonce": {
                    "type": "array",
                    "items": {
                        "type": "integer",
                        "format": "byte"
                    }
                },
                "scope_id": {
                    "type": "integer",
                    "example": 1
                },
                "subject_id": {
                    "type": "integer",
                    "example": 1
                },
                "subject_type": {
                    "type": "string",
                    "example": "user"
                },
                "wrap_algorithm": {
                    "type": "string",
                    "example": "ecdh-p256-hkdf-a256gcm"
                },
                "wrapped_key": {
                    "type": "array",
                    "items": {
                        "type": "integer",
                        "format": "byte"
                    }
                }
            }
        },
        "vault.KeyGrantsResponse": {
            "type": "object",
            "properties": {
                "grants": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/vault.KeyGrantResponse"
                    }
                }
            }
        },
        "vault.ScopeResponse": {
            "type": "object",
            "properties": {
                "grant_count": {
                    "type": "integer",
                    "example": 6
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "key_version": {
                    "type": "integer",
                    "example": 4
                },
                "ref_id": {
                    "type": "integer",
                    "example": 1
                },
                "rotated_at": {
                    "type": "string"
                },
                "scope_type": {
                    "type": "string",
                    "example": "vault"
                }
            }
        },
        "vault.ScopesResponse": {
            "type": "object",
            "properties": {
                "scopes": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/vault.ScopeResponse"
                    }
                }
            }
        },
        "vault.TreeResponse": {
            "type": "object",
            "properties": {
                "files": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/vault.FileResponse"
                    }
                },
                "folders": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/vault.FolderResponse"
                    }
                }
            }
        },
        "vault.VaultResponse": {
            "type": "object",
            "properties": {
                "change_seq": {
                    "type": "integer",
                    "example": 42
                },
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "meta": {
                    "type": "array",
                    "items": {
                        "type": "integer",
                        "format": "byte"
                    }
                },
                "meta_nonce": {
                    "type": "array",
                    "items": {
                        "type": "integer",
                        "format": "byte"
                    }
                },
                "owner_id": {
                    "type": "integer",
                    "example": 1
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "vault.VaultSummaryResponse": {
            "type": "object",
            "properties": {
                "change_seq": {
                    "type": "integer",
                    "example": 42
                },
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "key_scope_id": {
                    "type": "integer",
                    "example": 1
                },
                "key_state": {
                    "type": "string",
                    "example": "ok"
                },
                "key_version": {
                    "type": "integer",
                    "example": 1
                },
                "member_count": {
                    "type": "integer",
                    "example": 6
                },
                "meta": {
                    "type": "array",
                    "items": {
                        "type": "integer",
                        "format": "byte"
                    }
                },
                "meta_nonce": {
                    "type": "array",
                    "items": {
                        "type": "integer",
                        "format": "byte"
                    }
                },
                "note_count": {
                    "type": "integer",
                    "example": 213
                },
                "owner_id": {
                    "type": "integer",
                    "example": 1
                },
                "role": {
                    "type": "string",
                    "example": "owner"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "vault.VaultsResponse": {
            "type": "object",
            "properties": {
                "vaults": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/vault.VaultSummaryResponse"
                    }
                }
            }
        },
        "vault.bulkFilesRequest": {
            "type": "object",
            "required": [
                "ids"
            ],
            "properties": {
                "ids": {
                    "type": "array",
                    "maxItems": 200,
                    "minItems": 1,
                    "items": {
                        "type": "integer"
                    }
                }
            }
        },
        "vault.createFileRequest": {
            "type": "object",
            "required": [
                "content",
                "content_nonce",
                "key_scope_id",
                "key_version",
                "meta",
                "meta_nonce"
            ],
            "properties": {
                "content": {
                    "type": "array",
                    "maxItems": 4194304,
                    "minItems": 16,
                    "items": {
                        "type": "integer",
                        "format": "byte"
                    }
                },
                "content_nonce": {
                    "type": "array",
                    "maxItems": 32,
                    "minItems": 12,
                    "items": {
                        "type": "integer",
                        "format": "byte"
                    }
                },
                "folder_id": {
                    "type": "integer",
                    "minimum": 1
                },
                "key_scope_id": {
                    "type": "integer",
                    "minimum": 1
                },
                "key_version": {
                    "type": "integer",
                    "minimum": 1
                },
                "meta": {
                    "type": "array",
                    "maxItems": 8192,
                    "minItems": 16,
                    "items": {
                        "type": "integer",
                        "format": "byte"
                    }
                },
                "meta_nonce": {
                    "type": "array",
                    "maxItems": 32,
                    "minItems": 12,
                    "items": {
                        "type": "integer",
                        "format": "byte"
                    }
                }
            }
        },
        "vault.createFolderRequest": {
            "type": "object",
            "required": [
                "key_scope_id",
                "key_version",
                "meta",
                "meta_nonce"
            ],
            "properties": {
                "key_scope_id": {
                    "description": "KeyScopeID and KeyVersion declare which key the blobs were sealed under. The server\nrefuses them when they do not match the destination, because the row would be\nunreadable to everyone who can see it.",
                    "type": "integer",
                    "minimum": 1
                },
                "key_version": {
                    "type": "integer",
                    "minimum": 1
                },
                "meta": {
                    "type": "array",
                    "maxItems": 8192,
                    "minItems": 16,
                    "items": {
                        "type": "integer",
                        "format": "byte"
                    }
                },
                "meta_nonce": {
                    "type": "array",
                    "maxItems": 32,
                    "minItems": 12,
                    "items": {
                        "type": "integer",
                        "format": "byte"
                    }
                },
                "parent_id": {
                    "type": "integer",
                    "minimum": 1
                },
                "position": {
                    "type": "integer",
                    "minimum": 0
                }
            }
        },
        "vault.createVaultRequest": {
            "type": "object",
            "required": [
                "key_nonce",
                "meta",
                "meta_nonce",
                "wrapped_key"
            ],
            "properties": {
                "key_nonce": {
                    "type": "array",
                    "maxItems": 32,
                    "minItems": 12,
                    "items": {
                        "type": "integer",
                        "format": "byte"
                    }
                },
                "meta": {
                    "type": "array",
                    "maxItems": 8192,
                    "minItems": 16,
                    "items": {
                        "type": "integer",
                        "format": "byte"
                    }
                },
                "meta_nonce": {
                    "type": "array",
                    "maxItems": 32,
                    "minItems": 12,
                    "items": {
                        "type": "integer",
                        "format": "byte"
                    }
                },
                "wrap_algorithm": {
                    "description": "Algorithm names the sealed-box format, so a later format can be told apart.",
                    "type": "string",
                    "maxLength": 64
                },
                "wrapped_key": {
                    "description": "WrappedKey is the vault content key sealed to the creator's own public key.",
                    "type": "array",
                    "maxItems": 1024,
                    "minItems": 32,
                    "items": {
                        "type": "integer",
                        "format": "byte"
                    }
                }
            }
        },
        "vault.moveRequest": {
            "type": "object",
            "properties": {
                "parent_id": {
                    "type": "integer",
                    "minimum": 1
                },
                "position": {
                    "type": "integer",
                    "minimum": 0
                }
            }
        },
        "vault.updateContentRequest": {
            "type": "object",
            "required": [
                "content",
                "content_nonce"
            ],
            "properties": {
                "content": {
                    "type": "array",
                    "maxItems": 4194304,
                    "minItems": 16,
                    "items": {
                        "type": "integer",
                        "format": "byte"
                    }
                },
                "content_nonce": {
                    "type": "array",
                    "maxItems": 32,
                    "minItems": 12,
                    "items": {
                        "type": "integer",
                        "format": "byte"
                    }
                }
            }
        },
        "vault.updateMetaRequest": {
            "type": "object",
            "required": [
                "meta",
                "meta_nonce"
            ],
            "properties": {
                "meta": {
                    "type": "array",
                    "maxItems": 8192,
                    "minItems": 16,
                    "items": {
                        "type": "integer",
                        "format": "byte"
                    }
                },
                "meta_nonce": {
                    "type": "array",
                    "maxItems": 32,
                    "minItems": 12,
                    "items": {
                        "type": "integer",
                        "format": "byte"
                    }
                },
                "position": {
                    "type": "integer",
                    "minimum": 0
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "JWT token in the format: Bearer {token}",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{"http", "https"},
	Title:            "Shelf API",
	Description:      "REST API of the Shelf service.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
